export const TYPES ={ 
  GET_PROYECTOS:'GET_PROYECTOS',//ok
  GET_NAME_PROYECTOS: 'GET_NAME_PROYECTOS', 
  PROYECTO:'PROYECTO', //ok
  SELECT_PROYECTO: 'SELECT_PROYECTO',
  CALL_PROYECTOS_ACTIVOS_NAME: 'CALL_PROYECTOS_ACTIVOS_NAME',  //ok
  CALL_PROYECTOS_DESACTIVADOS_NAME:'CALL_PROYECTOS_DESACTIVADOS_NAME', //ok
  CALL_PROYECTOS_ADICIONALES_NAME: 'CALL_PROYECTOS_ADICIONALES_NAME',
  CALL_PROYECTOS_GARANTIA_NAME: 'CALL_PROYECTOS_GARANTIA_NAME',
  CALL_TOTAL: 'CALL_TOTAL',
    ACTIVA_PROYECTO:'ACTIVA_PROYECTO',
    DESACTIVA_PROYECTO:'DESACTIVA_PROYECTO', 
    
    ASIGNADO_CHECADOR: 'ASIGNADO_CHECADOR', 


    
   USUARIO_DATA:'USUARIO_DATA',
      
    
    
    USUARIOS_ACTIVOS:'USUARIOS_ACTIVOS', 
    USUARIOS_INACTIVOS:'USUARIOS_INACTIVOS', 
    USUARIOS_DESOCUPADOS: 'USUARIOS_DESOCUPADOS', 
    USUARIOS_OCUPADOS:'USUARIOS_OCUPADOS',
    USUARIOS_DISPONIBLES_CHECADOR:'USUARIOS_DISPONIBLES_CHECADOR', 
    REDUCER_USER_CHECADOR:'REDUCER_USER_CHECADOR',
    FETCH_ONLYUSER:'FETCH_ONLYUSER',
    
 TEST_TEST:'TEST_TEST'

  

    
}