export const TYPES ={ 
   //ASIGNACION 
    CALL_PROYECTOS_ACTIVOS: 'CALL_PROYECTOS_ACTIVOS', 
    CALL_PROYECTOS_DESACTIVADOS:'CALL_PROYECTOS_DESACTIVADOS',
    ACTIVA_PROYECTO:'ACTIVA_PROYECTO',
    DESACTIVA_PROYECTO:'DESACTIVA_PROYECTO', 
    ID_PROYECTO:'ID_PROYECTO', 
    ASIGNADO_CHECADOR: 'ASIGNADO_CHECADOR', 
    PROYECTO:'PROYECTO', 


    //USUARIO_SESION
      USUARIO_DATA:'USUARIO_DATA',
      
    
    //USUARIOS

    //ASISTENCIAS

    //ALMACEN

    
}