export const TYPES ={ 
    GET_PROYECTOS:'GET_PROYECTOS',
    CALL_PROYECTOS_ACTIVOS: 'CALL_PROYECTOS_ACTIVOS', 
    CALL_PROYECTOS_DESACTIVADOS:'CALL_PROYECTOS_DESACTIVADOS',
    ACTIVA_PROYECTO:'ACTIVA_PROYECTO',
    DESACTIVA_PROYECTO:'DESACTIVA_PROYECTO', 
    
    ASIGNADO_CHECADOR: 'ASIGNADO_CHECADOR', 
    PROYECTO:'PROYECTO', 


    
      USUARIO_DATA:'USUARIO_DATA',
      
    
    
    USUARIOS_ACTIVOS:'USUARIOS_ACTIVOS', 
    USUARIOS_INACTIVOS:'USUARIOS_INACTIVOS', 
    USUARIOS_DESOCUPADOS: 'USUARIOS_DESOCUPADOS', 
    USUARIOS_OCUPADOS:'USUARIOS_OCUPADOS',
    USUARIOS_DISPONIBLES_CHECADOR:'USUARIOS_DISPONIBLES_CHECADOR', 
    REDUCER_USER_CHECADOR:'REDUCER_USER_CHECADOR',
    FETCH_ONLYUSER:'FETCH_ONLYUSER',
    


  

    
}